# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [1]:
import pandas as pd
import plotly.express as px

# Notebook Presentation

In [2]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [3]:
df_apps = pd.read_csv('apps.csv')
df_apps.head() # head first 5 rows
df_apps.tail() # tail last 5 rows
df_apps.columns # show columns' names
df_apps.shape # rows and columns  count
df_apps.sample(n=5) # sample of nth random rows

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
6671,Bengali Newspaper - The first L.,NEWS_AND_MAGAZINES,4.00,11908,5.50,"1,000,000",Free,0,Everyone,News & Magazines,"July 1, 2018",4.1 and up
2011,Basket Manager 2017 Pro,SPORTS,4.70,163,4.60,"1,000",Paid,$0.99,Everyone,Sports,"October 6, 2017",4.1 and up
2598,Florida Tides & Weather,WEATHER,3.80,30,2.00,"1,000",Paid,$6.99,Everyone,Weather,"May 6, 2015",2.3 and up
9372,ADW Launcher 2,PERSONALIZATION,4.30,181399,6.15,"10,000,000",Free,0,Everyone,Personalization,"December 8, 2017",Varies with device
10535,Motorola FM Radio,VIDEO_PLAYERS,3.90,54807,4.65,"100,000,000",Free,0,Everyone,Video Players & Editors,"May 2, 2018",Varies with device

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [4]:
print(f'df_apps has {df_apps.shape[0]} rows and {df_apps.shape[1]} columns')

df_apps has 10841 rows and 12 columns

In [5]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [6]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
5398,Florida Lottery Results,NEWS_AND_MAGAZINES,4.10,763,2.20,"100,000",Free,0,Everyone,News & Magazines,"December 18, 2015",2.3.3 and up
7998,Carros Rebaixados BR,GAME,4.30,20691,89.00,"1,000,000",Free,0,Everyone,Racing,"July 31, 2018",4.4 and up
2749,Free Resume Builder – CV Maker,BUSINESS,4.40,25,12.00,"5,000",Free,0,Everyone,Business,"June 9, 2018",4.4 and up
7629,Zombie Hunter King,GAME,4.30,10306,50.00,"1,000,000",Free,0,Mature 17+,Action,"August 1, 2018",2.3 and up
74,DN Snacks,BUSINESS,NaN,0,7.60,1,Free,0,Everyone,Business,"April 9, 2018",4.0 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [7]:
df_apps.head(n = 1)
df_apps.drop(columns = ['Last_Updated','Android_Ver'], inplace = True, errors = 'ignore')
df_apps.sample(n = 1)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3503,DB TOS - Pocket Helper,TOOLS,4.20,265,3.40,"10,000",Free,0,Everyone,Tools

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [8]:
pd.options.display.float_format = '{:_.0f}'.format
df_apps.apply(lambda col: col.isna().value_counts(),axis = 0)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
False,10_841,10_841,9367,10_841,10_841,10_841,10840,10_841,10_841,10_841
True,NaN,NaN,1474,NaN,NaN,NaN,1,NaN,NaN,NaN

In [9]:
df_apps.Type.isna().value_counts()

Type
False    10840
True         1
Name: count, dtype: int64

In [10]:
df_apps.Rating.isna().value_counts()

Rating
False    9367
True     1474
Name: count, dtype: int64

In [11]:
df_apps_clean = df_apps.dropna()
df_apps_clean.isna().any()
df_apps_clean.shape #9367 rows
df_apps.shape       #10841 rows

(10841, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [12]:
df_apps_clean.sample(n = 5)
df_apps_clean.App.duplicated().value_counts()
df_apps_clean.drop_duplicates(inplace = True, subset = ['App','Type','Price'])
df_apps_clean.shape
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]
duplicated_rows.groupby('App').count()
duplicated_rows.count()

App               0
Category          0
Rating            0
Reviews           0
Size_MBs          0
Installs          0
Type              0
Price             0
Content_Rating    0
Genres            0
dtype: int64

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [13]:
df_apps_clean.sort_values(by = ['Rating','Reviews','Installs'], ascending = False).head(n = 5)
df_apps_clean.sort_values(by = ['Reviews','Rating'], ascending = False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4,78158306,5,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4,69119316,4,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4,66577313,5,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4,56642847,4,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,5,44891723,98,"100,000,000",Free,0,Everyone 10+,Strategy
...,...,...,...,...,...,...,...,...,...,...
728,Truck Driving Test Class 3 BC,FAMILY,1,1,2,50,Paid,$1.49,Everyone,Education
1208,Thistletown CI,PRODUCTIVITY,1,1,7,100,Free,0,Everyone,Productivity
1271,MbH BM,MEDICAL,1,1,2,100,Free,0,Everyone,Medical
1314,CR Magazine,BUSINESS,1,1,8,100,Free,0,Everyone,Business
2416,BJ Bridge Standard American 2018,GAME,1,1,5,"1,000",Free,0,Everyone,Card

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [14]:
df_apps_clean.sort_values(by = 'Size_MBs', ascending = False).head(n = 20)
df_apps_clean[df_apps_clean['Size_MBs'] == 100].count()
# it seems app size at Android App Store is limited to 100MBs

App               14
Category          14
Rating            14
Reviews           14
Size_MBs          14
Installs          14
Type              14
Price             14
Content_Rating    14
Genres            14
dtype: int64

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [15]:
# df_apps_clean.value_counts(subset = ['Type'])
df_apps_clean.sort_values(by = 'Reviews', ascending = False).head(n = 50)
df_apps_clean.sort_values(by = 'Reviews', ascending = False).head(n = 50).value_counts(subset = ['Type'])

Type
Free    50
Name: count, dtype: int64

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [16]:
df_apps_clean.Content_Rating.value_counts()
ratings = df_apps_clean.value_counts(subset = 'Content_Rating')
ratings
ratings.index

Index(['Everyone', 'Teen', 'Mature 17+', 'Everyone 10+', 'Adults only 18+',
       'Unrated'],
      dtype='str', name='Content_Rating')

In [17]:
fig = px.pie(labels = ratings.index, values = ratings.values, title = 'Nice pie chart', names = ratings.index)
fig.update_traces(textposition = 'outside', textinfo = 'percent+label')
fig.show()

In [20]:
fig = px.pie(labels = ratings.index, values = ratings.values, title = 'Donut', names = ratings.index, hole = 0.3)
fig.update_traces(textposition = 'inside', textinfo = 'percent', textfont_size=15)
fig.add_contour()
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [68]:
# df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)
df_apps_clean.Installs.value_counts()
df_apps_clean_bak = df_apps_clean.copy(deep = True)
df_apps_clean_bak.Installs = df_apps_clean_bak.Installs.astype(str).str.replace(',','')
df_apps_clean_bak.Installs = df_apps_clean_bak.Installs.astype(float)
# df_apps_clean_bak.Installs = pd.to_numeric(df_apps_clean_bak.Installs) more elegant way
df_apps_clean_bak.groupby(by = 'Installs').count()

,App,Category,Rating,Reviews,Size_MBs,Type,Price,Content_Rating,Genres
Installs,,,,,,,,,
1,3,3,3,3,3,3,3,3,3
5,9,9,9,9,9,9,9,9,9
10,69,69,69,69,69,69,69,69,69
50,56,56,56,56,56,56,56,56,56
100,303,303,303,303,303,303,303,303,303
500,199,199,199,199,199,199,199,199,199
1_000,698,698,698,698,698,698,698,698,698
5_000,425,425,425,425,425,425,425,425,425
10_000,988,988,988,988,988,988,988,988,988
50_000,457,457,457,457,457,457,457,457,457
100_000,1096,1096,1096,1096,1096,1096,1096,1096,1096
500_000,504,504,504,504,504,504,504,504,504
1_000_000,1417,1417,1417,1417,1417,1417,1417,1417,1417
5_000_000,607,607,607,607,607,607,607,607,607
10_000_000,933,933,933,933,933,933,933,933,933
50_000_000,202,202,202,202,202,202,202,202,202
100_000_000,189,189,189,189,189,189,189,189,189
500_000_000,24,24,24,24,24,24,24,24,24
1_000_000_000,20,20,20,20,20,20,20,20,20

In [65]:
df_apps_clean_bak.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs            int64
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [67]:
pd.options.display.
df_apps_clean_bak.groupby(by = 'Installs').count().sort_values(by = 'Installs', ascending = False)

,App,Category,Rating,Reviews,Size_MBs,Type,Price,Content_Rating,Genres
Installs,,,,,,,,,
1000000000,20,20,20,20,20,20,20,20,20
500000000,24,24,24,24,24,24,24,24,24
100000000,189,189,189,189,189,189,189,189,189
50000000,202,202,202,202,202,202,202,202,202
10000000,933,933,933,933,933,933,933,933,933
5000000,607,607,607,607,607,607,607,607,607
1000000,1417,1417,1417,1417,1417,1417,1417,1417,1417
500000,504,504,504,504,504,504,504,504,504
100000,1096,1096,1096,1096,1096,1096,1096,1096,1096
50000,457,457,457,457,457,457,457,457,457
10000,988,988,988,988,988,988,988,988,988
5000,425,425,425,425,425,425,425,425,425
1000,698,698,698,698,698,698,698,698,698
500,199,199,199,199,199,199,199,199,199
100,303,303,303,303,303,303,303,303,303
50,56,56,56,56,56,56,56,56,56
10,69,69,69,69,69,69,69,69,69
5,9,9,9,9,9,9,9,9,9
1,3,3,3,3,3,3,3,3,3

In [69]:
df_apps_clean_bak.info()

<class 'pandas.DataFrame'>
Index: 8199 entries, 21 to 10835
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             8199 non-null   str
 1   Category        8199 non-null   str
 2   Rating          8199 non-null   float64
 3   Reviews         8199 non-null   int64
 4   Size_MBs        8199 non-null   float64
 5   Installs        8199 non-null   float64
 6   Type            8199 non-null   str
 7   Price           8199 non-null   str
 8   Content_Rating  8199 non-null   str
 9   Genres          8199 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 704.6 KB

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [87]:
df_apps_clean_bak.Price = df_apps_clean_bak.Price.astype(str).str.replace('$', '')
df_apps_clean_bak.Price = pd.to_numeric(df_apps_clean_bak.Price,downcast = 'float')
df_apps_clean_bak.head(n = 20)
df_apps_clean_bak.Price.dtype
df_apps_clean_bak.sort_values(by = 'Price', ascending = False).head(20)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
3946,I'm Rich - Trump Edition,LIFESTYLE,4,275,7,10_000,Paid,400,Everyone,Lifestyle
2394,I am Rich!,FINANCE,4,93,22,1_000,Paid,400,Everyone,Finance
2461,I AM RICH PRO PLUS,FINANCE,4,36,41,1_000,Paid,400,Everyone,Finance
1331,most expensive app (H),FAMILY,4,6,2,100,Paid,400,Everyone,Entertainment
3145,I am rich(premium),FINANCE,4,472,1,5_000,Paid,400,Everyone,Finance
2775,I Am Rich Pro,FAMILY,4,201,3,5_000,Paid,400,Everyone,Entertainment
5765,I am rich,LIFESTYLE,4,3547,2,100_000,Paid,400,Everyone,Lifestyle
3221,I am Rich Plus,FAMILY,4,856,9,10_000,Paid,400,Everyone,Entertainment
3554,💎 I'm rich,LIFESTYLE,4,718,26,10_000,Paid,400,Everyone,Lifestyle
3114,I am Rich,FINANCE,4,180,4,5_000,Paid,400,Everyone,Finance
4606,I Am Rich Premium,FINANCE,4,1867,5,50_000,Paid,400,Everyone,Finance
1946,I am rich (Most expensive app),FINANCE,4,129,3,1_000,Paid,400,Teen,Finance
3897,I Am Rich,FAMILY,4,217,5,10_000,Paid,390,Everyone,Entertainment
2193,I am extremely Rich,LIFESTYLE,3,41,3,1_000,Paid,380,Everyone,Lifestyle
3856,I am rich VIP,LIFESTYLE,4,411,3,10_000,Paid,300,Everyone,Lifestyle
2281,Vargo Anesthesia Mega App,MEDICAL,5,92,32,1_000,Paid,80,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4,6,1,100,Paid,40,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4,134,2,1_000,Paid,38,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,4,214,68,1_000,Paid,34,Everyone,Medical
2207,EMT PASS,MEDICAL,3,51,2,1_000,Paid,30,Everyone,Medical

### The most expensive apps sub $250

In [80]:
df_under_250 = df_apps_clean_bak[df_apps_clean_bak['Price'] < 250]
df_under_250.sort_values(by = 'Price', ascending = False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
2281,Vargo Anesthesia Mega App,MEDICAL,5,92,32,1_000,Paid,80,Everyone,Medical
1407,LTC AS Legal,MEDICAL,4,6,1,100,Paid,40,Everyone,Medical
2629,I am Rich Person,LIFESTYLE,4,134,2,1_000,Paid,38,Everyone,Lifestyle
2481,A Manual of Acupuncture,MEDICAL,4,214,68,1_000,Paid,34,Everyone,Medical
504,AP Art History Flashcards,FAMILY,5,1,96,10,Paid,30,Mature 17+,Education
...,...,...,...,...,...,...,...,...,...,...
171,ei Calc,TOOLS,5,2,19,10,Free,0,Everyone,Tools
162,CB Heroes,SOCIAL,5,5,2,5,Free,0,Everyone,Social
154,CZ-Help,BOOKS_AND_REFERENCE,5,2,1,5,Free,0,Everyone,Books & Reference
151,EB Cash Collections,BUSINESS,5,1,4,5,Free,0,Everyone,Business
82,Brick Breaker BR,GAME,5,7,19,5,Free,0,Everyone,Arcade

### Highest Grossing Paid Apps (ballpark estimate)

In [85]:
df_under_250_plus_revenue = df_under_250
df_under_250_plus_revenue['Revenue_Estimate'] = df_under_250.Price * df_under_250.Installs
df_under_250_plus_revenue.sort_values(by = 'Revenue_Estimate', ascending = False).head(10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Revenue_Estimate
9220,Minecraft,FAMILY,4,2376564,19,10_000_000,Paid,7,Everyone 10+,Arcade;Action & Adventure,69_900_000
8825,Hitman Sniper,GAME,5,408292,29,10_000_000,Paid,1,Mature 17+,Action,9_900_000
7151,Grand Theft Auto: San Andreas,GAME,4,348962,26,1_000_000,Paid,7,Mature 17+,Action,6_990_000
7477,Facetune - For Free,PHOTOGRAPHY,4,49553,48,1_000_000,Paid,6,Everyone,Photography,5_990_000
7977,Sleep as Android Unlock,LIFESTYLE,4,23966,1,1_000_000,Paid,6,Everyone,Lifestyle,5_990_000
6594,DraStic DS Emulator,GAME,5,87766,12,1_000_000,Paid,5,Everyone,Action,4_990_000
6082,Weather Live,WEATHER,4,76593,5,500_000,Paid,6,Everyone,Weather,2_995_000
6746,Card Wars - Adventure Time,FAMILY,4,129603,23,1_000_000,Paid,3,Everyone 10+,Card;Action & Adventure,2_990_000
7633,Five Nights at Freddy's,GAME,5,100805,50,1_000_000,Paid,3,Teen,Action,2_990_000
7954,Bloons TD 5,FAMILY,5,190086,94,1_000_000,Paid,3,Everyone,Strategy,2_990_000

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [89]:
df_apps_clean_bak.Category.nunique()

33

In [96]:
top_ten = df_apps_clean_bak.Category.value_counts()[:10]
top_ten

Category
FAMILY             1610
GAME                910
TOOLS               719
LIFESTYLE           302
FINANCE             302
PRODUCTIVITY        301
PERSONALIZATION     298
MEDICAL             292
PHOTOGRAPHY         263
BUSINESS            262
Name: count, dtype: int64

In [101]:
bar = px.bar(top_ten)
bar.write_html(file = './bar_with_values_mod.html', include_plotlyjs = 'cdn')
bar.show()

In [103]:
bar = px.bar(x = top_ten.index, y = top_ten.values)
bar.show()

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [112]:

bar = px.bar(x = top_ten.index, y = top_ten.values, orientation = 'v')
bar.show()

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [119]:
bar = px.bar(y = top_ten.index, x = top_ten.values, orientation = 'h')
bar.show()

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [127]:

category_installs = df_apps_clean_bak.groupby(by = 'Category').aggregate({'Installs': pd.Series.sum})
category_installs.sort_values(by = 'Installs', ascending = True, inplace = True)
category_installs

                          Installs
Category
EVENTS                  15_949_410
BEAUTY                  26_916_200
PARENTING               31_116_110
MEDICAL                 39_162_676
COMICS                  44_931_100
LIBRARIES_AND_DEMO      52_083_000
AUTO_AND_VEHICLES       53_129_800
HOUSE_AND_HOME          97_082_000
ART_AND_DESIGN         114_233_100
DATING                 140_912_410
FOOD_AND_DRINK         211_677_750
EDUCATION              352_852_000
WEATHER                361_096_500
FINANCE                455_312_400
MAPS_AND_NAVIGATION    503_267_560
LIFESTYLE              503_742_120
BUSINESS               692_018_120
SPORTS               1_096_431_465
HEALTH_AND_FITNESS   1_134_006_220
SHOPPING             1_400_331_540
PERSONALIZATION      1_532_352_930
BOOKS_AND_REFERENCE  1_665_791_655
ENTERTAINMENT        2_113_660_000
NEWS_AND_MAGAZINES   2_369_110_650
TRAVEL_AND_LOCAL     2_894_859_300
VIDEO_PLAYERS        3_916_897_200
FAMILY               4_437_579_590
PHOTOGRAPHY          4_649_143_130
SOCIAL               5_487_841_475
PRODUCTIVITY         5_788_070_180
TOOLS                8_099_724_500
COMMUNICATION       11_039_241_530
GAME                13_858_762_717

In [128]:
h_bar = px.bar(y = category_installs.index, x = category_installs.Installs, orientation = 'h', title = 'Category Popularity')
h_bar.update_layout(xaxis_title = 'Number of Downloads', yaxis_title = 'Category')
h_bar.show()

# Challenge
As a challenge, let's use plotly to create a scatter plot that looks like this:
xD

In [177]:

category_installs_mod = df_apps_clean_bak.groupby(by = 'Category').aggregate({'App': pd.Series.count, 'Installs': pd.Series.sum, })
category_installs_mod.sort_values(by = 'Installs', ascending = False)
category_installs_mod['Concentration_indicator'] = category_installs_mod.Installs / category_installs_mod.App
category_installs_mod = category_installs_mod.sort_values(by = 'Concentration_indicator', ascending = False)
category_installs.head()
df_apps_clean_bak.head()

mix = px.scatter(title = 'Category Concentration',x=category_installs_mod.App, y = category_installs_mod.Installs)
mix.update_layout(yaxis_title = 'Installs', xaxis_title = 'Number of Apps (Lower=More Concentrated)')
mix.show()
# category_installs_mod.head()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [181]:
df_apps_clean_bak.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
21,KBA-EZ Health Guide,MEDICAL,5,4,25,1,Free,0,Everyone,Medical
28,Ra Ga Ba,GAME,5,2,20,1,Paid,1,Everyone,Arcade
47,Mu.F.O.,GAME,5,2,16,1,Paid,1,Everyone,Arcade
82,Brick Breaker BR,GAME,5,7,19,5,Free,0,Everyone,Arcade
99,Anatomy & Physiology Vocabulary Exam Review App,MEDICAL,5,1,5,5,Free,0,Everyone,Medical

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

# Grouped Bar Charts: Free vs. Paid Apps per Category

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.