# Introduction

In this notebook, we will do a comprehensive analysis of the Android app market by comparing thousands of apps in the Google Play store.

# About the Dataset of Google Play Store Apps & Reviews

**Data Source:** <br>
App and review data was scraped from the Google Play Store by Lavanya Gupta in 2018. Original files listed [here](
https://www.kaggle.com/lava18/google-play-store-apps).

# Import Statements

In [23]:
#region import
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
#endregion

# Notebook Presentation

In [24]:
# Show numeric output in decimal format e.g., 2.15
pd.options.display.float_format = '{:,.2f}'.format

# Read the Dataset

In [25]:
df_apps = pd.read_csv('apps.csv')
df_apps.head() # head first 5 rows
df_apps.tail() # tail last 5 rows
df_apps.columns # show columns' names
df_apps.shape # rows and columns  count
df_apps.sample(n=5) # sample of nth random rows

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
2004,Doctor Finder CY,MEDICAL,4.90,57,6.10,"1,000",Free,0,Everyone,Medical,"November 11, 2015",3.0 and up
9386,HTC Mail,PRODUCTIVITY,3.10,6572,4.00,"10,000,000",Free,0,Everyone,Productivity,"May 29, 2018",Varies with device
4582,AK 47 Guns Wallpaper,PERSONALIZATION,4.20,322,6.80,"50,000",Free,0,Everyone,Personalization,"May 29, 2017",4.1 and up
339,AJ Gray Dark Icon Pack,PERSONALIZATION,5.00,2,35.00,10,Paid,$0.99,Everyone,Personalization,"April 29, 2018",4.1 and up
6812,Nature Sounds,LIFESTYLE,4.80,28588,24.00,"1,000,000",Free,0,Everyone,Lifestyle,"March 1, 2018",4.0.3 and up

# Data Cleaning

**Challenge**: How many rows and columns does `df_apps` have? What are the column names? Look at a random sample of 5 different rows with [.sample()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html).

In [26]:
print(f'df_apps has {df_apps.shape[0]} rows and {df_apps.shape[1]} columns')

df_apps has 10841 rows and 12 columns

In [27]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='str')

In [28]:
df_apps.sample(n=5)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
5438,CHRONO TRIGGER (Upgrade Ver.),FAMILY,3.80,11250,6.30,"100,000",Paid,$9.99,Everyone 10+,Role Playing,"June 12, 2018",4.2 and up
8236,Yahoo Finance,FINANCE,4.40,135952,9.15,"5,000,000",Free,0,Everyone,Finance,"July 30, 2018",Varies with device
10496,ZEDGE™ Ringtones & Wallpapers,PERSONALIZATION,4.60,6466641,6.15,"100,000,000",Free,0,Teen,Personalization,"July 19, 2018",Varies with device
3690,Casper Ssinema,VIDEO_PLAYERS,3.30,1261,2.50,"10,000",Free,0,Everyone,Video Players & Editors,"October 30, 2014",2.3 and up
1133,MouseMingle,DATING,2.70,3,3.90,100,Free,0,Mature 17+,Dating,"July 17, 2018",4.4 and up

### Drop Unused Columns

**Challenge**: Remove the columns called `Last_Updated` and `Android_Version` from the DataFrame. We will not use these columns.

In [29]:
df_apps.head(n = 1)
df_apps.drop(columns = ['Last_Updated','Android_Ver'], inplace = True, errors = 'ignore')
df_apps.sample(n = 1)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
5729,Beauty Rental Shop,FAMILY,4.60,11480,93.00,"100,000",Free,0,Everyone,Simulation

### Find and Remove NaN values in Ratings

**Challenge**: How may rows have a NaN value (not-a-number) in the Ratings column? Create DataFrame called `df_apps_clean` that does not include these rows.

In [30]:
pd.options.display.float_format = '{:_.0f}'.format
df_apps.apply(lambda col: col.isna().value_counts(),axis = 0)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
False,10_841,10_841,9367,10_841,10_841,10_841,10840,10_841,10_841,10_841
True,NaN,NaN,1474,NaN,NaN,NaN,1,NaN,NaN,NaN

In [31]:
df_apps.Type.isna().value_counts()

Type
False    10840
True         1
Name: count, dtype: int64

In [32]:
df_apps.Rating.isna().value_counts()

Rating
False    9367
True     1474
Name: count, dtype: int64

In [33]:
df_apps_clean = df_apps.dropna()
df_apps_clean.isna().any()
df_apps_clean.shape #9367 rows
df_apps.shape       #10841 rows

(10841, 10)

### Find and Remove Duplicates

**Challenge**: Are there any duplicates in data? Check for duplicates using the [.duplicated()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html) function. How many entries can you find for the "Instagram" app? Use [.drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) to remove any duplicates from `df_apps_clean`.

In [34]:
df_apps_clean.sample(n = 5)
df_apps_clean.App.duplicated().value_counts()
df_apps_clean.drop_duplicates(inplace = True, subset = ['App','Type','Price'])
df_apps_clean.shape
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]
duplicated_rows.groupby('App').count()
duplicated_rows.count()

App               0
Category          0
Rating            0
Reviews           0
Size_MBs          0
Installs          0
Type              0
Price             0
Content_Rating    0
Genres            0
dtype: int64

# Find Highest Rated Apps

**Challenge**: Identify which apps are the highest rated. What problem might you encounter if you rely exclusively on ratings alone to determine the quality of an app?

In [35]:
df_apps_clean.sort_values(by = ['Rating','Reviews','Installs'], ascending = False).head(n = 5)
df_apps_clean.sort_values(by = ['Reviews','Rating'], ascending = False)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10805,Facebook,SOCIAL,4,78158306,5,"1,000,000,000",Free,0,Teen,Social
10785,WhatsApp Messenger,COMMUNICATION,4,69119316,4,"1,000,000,000",Free,0,Everyone,Communication
10806,Instagram,SOCIAL,4,66577313,5,"1,000,000,000",Free,0,Teen,Social
10784,Messenger – Text and Video Chat for Free,COMMUNICATION,4,56642847,4,"1,000,000,000",Free,0,Everyone,Communication
10650,Clash of Clans,GAME,5,44891723,98,"100,000,000",Free,0,Everyone 10+,Strategy
...,...,...,...,...,...,...,...,...,...,...
728,Truck Driving Test Class 3 BC,FAMILY,1,1,2,50,Paid,$1.49,Everyone,Education
1208,Thistletown CI,PRODUCTIVITY,1,1,7,100,Free,0,Everyone,Productivity
1271,MbH BM,MEDICAL,1,1,2,100,Free,0,Everyone,Medical
1314,CR Magazine,BUSINESS,1,1,8,100,Free,0,Everyone,Business
2416,BJ Bridge Standard American 2018,GAME,1,1,5,"1,000",Free,0,Everyone,Card

# Find 5 Largest Apps in terms of Size (MBs)

**Challenge**: What's the size in megabytes (MB) of the largest Android apps in the Google Play Store. Based on the data, do you think there could be limit in place or can developers make apps as large as they please?

In [36]:
df_apps_clean.sort_values(by = 'Size_MBs', ascending = False).head(n = 20)
df_apps_clean[df_apps_clean['Size_MBs'] == 100].count()
# it seems app size at Android App Store is limited to 100MBs

App               14
Category          14
Rating            14
Reviews           14
Size_MBs          14
Installs          14
Type              14
Price             14
Content_Rating    14
Genres            14
dtype: int64

# Find the 5 App with Most Reviews

**Challenge**: Which apps have the highest number of reviews? Are there any paid apps among the top 50?

In [37]:
# df_apps_clean.value_counts(subset = ['Type'])
df_apps_clean.sort_values(by = 'Reviews', ascending = False).head(n = 50)
df_apps_clean.sort_values(by = 'Reviews', ascending = False).head(n = 50).value_counts(subset = ['Type'])

Type
Free    50
Name: count, dtype: int64

# Plotly Pie and Donut Charts - Visualise Categorical Data: Content Ratings

In [38]:
df_apps_clean.Content_Rating.value_counts()
ratings = df_apps_clean.value_counts(subset = 'Content_Rating')
ratings
ratings.index

Index(['Everyone', 'Teen', 'Mature 17+', 'Everyone 10+', 'Adults only 18+',
       'Unrated'],
      dtype='str', name='Content_Rating')

In [39]:
fig = px.pie(labels = ratings.index, values = ratings.values, title = 'Nice pie chart', names = ratings.index)
fig.update_traces(textposition = 'outside', textinfo = 'percent+label')
fig.show()

In [40]:
fig = px.pie(labels = ratings.index, values = ratings.values, title = 'Donut', names = ratings.index, hole = 0.3)
fig.update_traces(textposition = 'inside', textinfo = 'percent', textfont_size=15)
fig.add_contour()
fig.show()

# Numeric Type Conversion: Examine the Number of Installs

**Challenge**: How many apps had over 1 billion (that's right - BILLION) installations? How many apps just had a single install? 

Check the datatype of the Installs column.

Count the number of apps at each level of installations. 

Convert the number of installations (the Installs column) to a numeric data type. Hint: this is a 2-step process. You'll have make sure you remove non-numeric characters first.

In [41]:
# df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)
df_apps_clean.Installs.value_counts()
df_apps_clean_bak = df_apps_clean.copy(deep = True)
df_apps_clean_bak.Installs = df_apps_clean_bak.Installs.astype(str).str.replace(',','')
df_apps_clean_bak.Installs = df_apps_clean_bak.Installs.astype(float)
# df_apps_clean_bak.Installs = pd.to_numeric(df_apps_clean_bak.Installs) more elegant way
df_apps_clean_bak.groupby(by = 'Installs').count()

,App,Category,Rating,Reviews,Size_MBs,Type,Price,Content_Rating,Genres
Installs,,,,,,,,,
1,3,3,3,3,3,3,3,3,3
5,9,9,9,9,9,9,9,9,9
10,69,69,69,69,69,69,69,69,69
50,56,56,56,56,56,56,56,56,56
100,303,303,303,303,303,303,303,303,303
500,199,199,199,199,199,199,199,199,199
1_000,698,698,698,698,698,698,698,698,698
5_000,425,425,425,425,425,425,425,425,425
10_000,988,988,988,988,988,988,988,988,988
50_000,457,457,457,457,457,457,457,457,457
100_000,1096,1096,1096,1096,1096,1096,1096,1096,1096
500_000,504,504,504,504,504,504,504,504,504
1_000_000,1417,1417,1417,1417,1417,1417,1417,1417,1417
5_000_000,607,607,607,607,607,607,607,607,607
10_000_000,933,933,933,933,933,933,933,933,933
50_000_000,202,202,202,202,202,202,202,202,202
100_000_000,189,189,189,189,189,189,189,189,189
500_000_000,24,24,24,24,24,24,24,24,24
1_000_000_000,20,20,20,20,20,20,20,20,20

In [42]:
df_apps_clean_bak.dtypes

App                   str
Category              str
Rating            float64
Reviews             int64
Size_MBs          float64
Installs          float64
Type                  str
Price                 str
Content_Rating        str
Genres                str
dtype: object

In [43]:
(df_apps_clean_bak.groupby(by = 'Installs')
 .count().sort_values(by = 'Installs', ascending = False))

SyntaxError: invalid syntax (982502663.py, line 1)

In [ ]:
df_apps_clean_bak.info()

# Find the Most Expensive Apps, Filter out the Junk, and Calculate a (ballpark) Sales Revenue Estimate

Let's examine the Price column more closely.

**Challenge**: Convert the price column to numeric data. Then investigate the top 20 most expensive apps in the dataset.

Remove all apps that cost more than $250 from the `df_apps_clean` DataFrame.

Add a column called 'Revenue_Estimate' to the DataFrame. This column should hold the price of the app times the number of installs. What are the top 10 highest grossing paid apps according to this estimate? Out of the top 10 highest grossing paid apps, how many are games?

In [ ]:
df_apps_clean_bak.Price = df_apps_clean_bak.Price.astype(str).str.replace('$', '')
df_apps_clean_bak.Price = pd.to_numeric(df_apps_clean_bak.Price,downcast = 'float')
df_apps_clean_bak.head(n = 20)
df_apps_clean_bak.Price.dtype
df_apps_clean_bak.sort_values(by = 'Price', ascending = False).head(20)

### The most expensive apps sub $250

In [ ]:
df_under_250 = df_apps_clean_bak[df_apps_clean_bak['Price'] < 250]
df_under_250.sort_values(by = 'Price', ascending = False)

### Highest Grossing Paid Apps (ballpark estimate)

In [ ]:
df_under_250_plus_revenue = df_under_250
df_under_250_plus_revenue['Revenue_Estimate'] = df_under_250.Price * df_under_250.Installs
df_under_250_plus_revenue.sort_values(by = 'Revenue_Estimate', ascending = False).head(10)

# Plotly Bar Charts & Scatter Plots: Analysing App Categories

In [ ]:
df_apps_clean_bak.Category.nunique()

In [ ]:
top_ten = df_apps_clean_bak.Category.value_counts()[:10]
top_ten

In [1]:
bar = px.bar(top_ten)
bar.write_html(file = './bar_with_values_mod.html', include_plotlyjs = 'cdn')
bar.show()

NameError: name 'px' is not defined

In [ ]:
bar = px.bar(x = top_ten.index, y = top_ten.values)
bar.show()

### Vertical Bar Chart - Highest Competition (Number of Apps)

In [ ]:
bar = px.bar(x = top_ten.index, y = top_ten.values, orientation = 'v')
bar.show()

### Horizontal Bar Chart - Most Popular Categories (Highest Downloads)

In [ ]:
bar = px.bar(y = top_ten.index, x = top_ten.values, orientation = 'h')
bar.show()

### Category Concentration - Downloads vs. Competition

**Challenge**: 
* First, create a DataFrame that has the number of apps in one column and the number of installs in another:

<img src=https://imgur.com/uQRSlXi.png width="350">

* Then use the [plotly express examples from the documentation](https://plotly.com/python/line-and-scatter/) alongside the [.scatter() API reference](https://plotly.com/python-api-reference/generated/plotly.express.scatter.html)to create scatter plot that looks like this. 

<img src=https://imgur.com/cHsqh6a.png>

*Hint*: Use the size, hover_name and color parameters in .scatter(). To scale the yaxis, call .update_layout() and specify that the yaxis should be on a log-scale like so: yaxis=dict(type='log')

In [ ]:
category_installs = df_apps_clean_bak.groupby(by = 'Category').aggregate({'Installs': pd.Series.sum})
category_installs.sort_values(by = 'Installs', ascending = True, inplace = True)
category_installs

In [ ]:
h_bar = px.bar(y = category_installs.index, x = category_installs.Installs, orientation = 'h', title = 'Category Popularity')
h_bar.update_layout(xaxis_title = 'Number of Downloads', yaxis_title = 'Category')
h_bar.show()

# Challenge
As a challenge, let's use plotly to create a scatter plot that looks like this:
xD

In [ ]:
category_installs_mod = df_apps_clean_bak.groupby(by = 'Category').aggregate({'App': pd.Series.count, 'Installs': pd.Series.sum, })
category_installs_mod.sort_values(by = 'Installs', ascending = False)
category_installs_mod['Concentration_indicator'] = category_installs_mod.Installs / category_installs_mod.App
category_installs_mod = category_installs_mod.sort_values(by = 'Concentration_indicator', ascending = False)
category_installs.head()
df_apps_clean_bak.head()

mix = px.scatter(title = 'Category Concentration',x=category_installs_mod.App, y = category_installs_mod.Installs)
mix.update_layout(yaxis_title = 'Installs', xaxis_title = 'Number of Apps (Lower=More Concentrated)')
mix.show()
# category_installs_mod.head()

In [ ]:
#question - is this below is equal to merge App and Installs independent on = Category? Let's find out!
category_installs_mod = df_apps_clean_bak.groupby(by = 'Category').aggregate({'App': pd.Series.count, 'Installs': pd.Series.sum, })
category_installs_mod.head(n = 10)

In [ ]:
df_apps_clean_bak.head()
to_merge_1 = df_apps_clean_bak.groupby(by = 'Category').agg({'Installs': pd.Series.sum})
to_merge_2 = df_apps_clean_bak.groupby(by = 'Category').agg({'App': pd.Series.count})
merged = pd.merge(left = to_merge_1, right = to_merge_2, how = 'inner', on = 'Category')
merged.head(n = 10)
#yep, this is exactly the same output as
# category_installs_mod = df_apps_clean_bak.groupby(by = 'Category').aggregate({'App': pd.Series.count, 'Installs': pd.Series.sum, })
mix = px.scatter(data_frame = merged, title = 'Category Concentration',x='App', y = 'Installs', size = 'App', hover_name = merged.index, color = 'Installs')
mix.update_layout(yaxis_title = 'Installs', xaxis_title = 'Number of Apps (Lower=More Concentrated)', yaxis = dict(type = 'log'))
mix.show()

# Extracting Nested Data from a Column

**Challenge**: How many different types of genres are there? Can an app belong to more than one genre? Check what happens when you use .value_counts() on a column with nested values? See if you can work around this problem by using the .split() function and the DataFrame's [.stack() method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html).

In [ ]:
df_apps_clean_bak.head()
# def my_func():
#   if pd.Series.nunique() > 1:
# tests = df_apps_clean_bak.groupby(by = 'Category').aggregate({'App':'count', 'Installs': 'sum', 'Genres': pd.Series})
# tests
df_apps_clean_bak.Genres.nunique()
df_apps_clean_bak.Genres.value_counts().sort_values()
stack = df_apps_clean_bak.Genres.str.split(';', expand = True).stack()
stack.value_counts()

In [ ]:
len(df_apps_clean_bak.Genres.unique())
df_apps_clean_bak.Genres.value_counts().sort_values(ascending=True)[:5]
stack = df_apps_clean_bak.Genres.str.split(';', expand = True).stack()
print(f'We now have a single column with shape: {stack.shape}')
num_genres = stack.value_counts()
print(f'Number of genres: {len(num_genres)}')

# Colour Scales in Plotly Charts - Competition in Genres

**Challenge**: Can you create this chart with the Series containing the genre data? 

<img src=https://imgur.com/DbcoQli.png width=400>

Try experimenting with the built in colour scales in Plotly. You can find a full list [here](https://plotly.com/python/builtin-colorscales/). 

* Find a way to set the colour scale using the color_continuous_scale parameter. 
* Find a way to make the color axis disappear by using coloraxis_showscale.

In [ ]:
bar = px.bar(x = num_genres.index[:15], # index = category name
             y = num_genres.values[:15], # count
             title='Top Genres',
             hover_name=num_genres.index[:15],
             color=num_genres.values[:15],
             color_continuous_scale='Agsunset')
bar.update_layout(xaxis_title='Genre',
yaxis_title='Number of Apps',
coloraxis_showscale=True)
bar.show()

# Grouped Bar Charts: Free vs. Paid Apps per Category

In [44]:
df_apps_clean_bak.value_counts()
df_free_vs_paid = df_apps_clean_bak.groupby(by = ['Category','Type'], as_index = True).agg({'App': pd.Series.count}) #as_index parameter is crucial here, it's about category and type are treated as index within creating new dataFrame
df_free_vs_paid.head(6)

                          App
Category            Type
ART_AND_DESIGN      Free   58
                    Paid    3
AUTO_AND_VEHICLES   Free   72
                    Paid    1
BEAUTY              Free   42
BOOKS_AND_REFERENCE Free  161

**Challenge**: Use the plotly express bar [chart examples](https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories) and the [.bar() API reference](https://plotly.com/python-api-reference/generated/plotly.express.bar.html#plotly.express.bar) to create this bar chart: 

<img src=https://imgur.com/LE0XCxA.png>

You'll want to use the `df_free_vs_paid` DataFrame that you created above that has the total number of free and paid apps per category. 

See if you can figure out how to get the look above by changing the `categoryorder` to 'total descending' as outlined in the documentation here [here](https://plotly.com/python/categorical-axes/#automatically-sorting-categories-by-name-or-total-value).

In [47]:
df_free_vs_paid.head(5)

                        App
Category          Type
ART_AND_DESIGN    Free   58
                  Paid    3
AUTO_AND_VEHICLES Free   72
                  Paid    1
BEAUTY            Free   42

In [48]:
df_free_vs_paid.sample(n = 5)
df_resetted = df_free_vs_paid.reset_index(allow_duplicates = True) #you can change multiIndex to normal columns using reset_index
df_resetted.head()
fig = go.Figure()
fig.add_trace(go.Bar(
  x = df_resetted.Type,
  y = df_resetted.Category,
  name = 'Type=Free'
))
fig.add_trace(go.Bar(
  x = df_resetted.Type,
  y = df_resetted.Category,
  name = 'Type=Paid'
))
fig.update_layout(barmode = 'group', title=dict(
  text='Free vs Paid Apps by Category'),
  xaxis=dict(
    categoryorder='category ascending',
    title=dict(
      text='Category',
      font=dict(
        size=16
      )
    )
  ),
  yaxis=dict(
    title=dict(
      text='Number of Apps',
      font=dict(
        size=16
      )
    )
  )
)
fig.show()

In [49]:
g_bar = px.bar(df_resetted,
               x='Category',
               y='App',
               title='Free vs Paid Apps by Category',
               color='Type',
               barmode='group')

g_bar.update_layout(xaxis_title='Category',
                    yaxis_title='Number of Apps',
                    xaxis={'categoryorder':'total descending'},
                    yaxis=dict(type='log'))

g_bar.show()

# Plotly Box Plots: Lost Downloads for Paid Apps

**Challenge**: Create a box plot that shows the number of Installs for free versus paid apps. How does the median number of installations compare? Is the difference large or small?

Use the [Box Plots Guide](https://plotly.com/python/box-plots/) and the [.box API reference](https://plotly.com/python-api-reference/generated/plotly.express.box.html) to create the following chart. 

<img src=https://imgur.com/uVsECT3.png>

In [57]:
df_resetted.head()
df_apps_clean
fig = px.box(data_frame = df_apps_clean, y = 'Installs', x = 'Type')
fig.show()

In [58]:
box = px.box(df_apps_clean,
             y='Installs',
             x='Type',
             color='Type',
             notched=True,
             points='all',
             title='How Many Downloads are Paid Apps Giving Up?')

box.update_layout(yaxis=dict(type='log'))

box.show()

# Plotly Box Plots: Revenue by App Category

**Challenge**: See if you can generate the chart below: 

<img src=https://imgur.com/v4CiNqX.png>

Looking at the hover text, how much does the median app earn in the Tools category? If developing an Android app costs $30,000 or thereabouts, does the average photography app recoup its development costs?

Hint: I've used 'min ascending' to sort the categories.

In [71]:

pd.options.display.float_format = '{:,.2f}'.format
df_paid_apps = df_apps_clean[df_apps_clean['Type'] == 'Paid']
df_paid_apps.head()
df_paid_apps.Price = df_paid_apps.Price.str.replace('$','')
df_paid_apps.Price = pd.to_numeric(df_paid_apps.Price, downcast = 'float')
df_paid_apps['Revenue_Estimated'] = df_paid_apps.Price * df_paid_apps.Price
df_paid_apps.head()
box = px.box(df_paid_apps,
             x='Category',
             y='Revenue_Estimated',
             title='How Much Can Paid Apps Earn?')

box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Ballpark Revenue',
                  xaxis={'categoryorder':'min ascending'},
                  yaxis=dict(type='log'))
box.show()

# How Much Can You Charge? Examine Paid App Pricing Strategies by Category

**Challenge**: What is the median price price for a paid app? Then compare pricing by category by creating another box plot. But this time examine the prices (instead of the revenue estimates) of the paid apps. I recommend using `{categoryorder':'max descending'}` to sort the categories.

In [77]:
df_paid_apps.Revenue_Estimated.median()
df_paid_apps.Price.median()

np.float32(2.99)

In [78]:
box = px.box(df_paid_apps,
             x='Category',
             y="Price",
             title='Price per Category')

box.update_layout(xaxis_title='Category',
                  yaxis_title='Paid App Price',
                  xaxis={'categoryorder':'max descending'},
                  yaxis=dict(type='log'))

box.show()